BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        on_press: app.handle_clear()
    Label:
        id: clear_output
    Button:
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label


    Button:
        text: 'Enter your name'
        color: (1, 1, 0, 1)

